= greetings-gae

A simple https://cloud.google.com/appengine/docs/java/[Google App
Engine] webapp, written in 100% https://clojure.org/[Clojure], built
with http://boot-clj.com/[Boot].

IMPORTANT: you do not need a GAE account to experiment!  The GAE SDK
contains everything you need to run webapps on the local devserver;
you only need a GAE account if you want to deploy to the production
servers.

[NOTE]
====
Use of App Engine services such as the Datastore is beyond the scope of
this example.  Its sole purpose is to demonstrate the how easy it is
to use https://github.com/migae/boot-gae[boot-gae] to get a Clojure
webapp up and running on GAE with a repl-like development environment.
====

== getting started

[source,shell]
----
$ git clone https://github.com/migae/boot-gae.git
$ cd boot-gae/tasklib
$ boot pom jar install
----

WARNING: The first time you run `boot` with the GAE Java SDK
dependency, the SDK zip file will be downloaded.  This is a large file
so it may take a _very_ long time; be patient.  To monitor progress,
use the `-vv` switch with the `boot` command, e.g. `$ boot -vv help`
will download the dependencies before showing the help screen, and
`-vv` will display download progress.  Once `$ boot pom jar install`
completes, run:

[source,clojure]
----
$ cd ../greetings-gae
$ ./boot.sh gae/build
$ ./boot.sh gae/run
----


NOTE: Use of `boot.sh` is optional; it uses the JVM options in
`./.boot-jvm-options`.  See
https://github.com/boot-clj/boot/wiki/JVM-Options[JVM Options].

WARNING: The GAE java sdk is quite large, so don't be alarmed if
`gae/build` takes a while to run the first time.

To get a repl-like dev environment, open a second terminal and start a
watcher:

[source,shell]
----
$ boot gae/watch
----

If you need to change the configuration, for example to add another
servlet, you'll have to restart the server.  Rerun `boot gae/build` to
reconfigure the webapp, then run `boot gae/run` again.

== troubleshooting

```
java.lang.NoClassDefFoundError: clojure/lang/Var
```

Check `<build-root>/WEB-INF/lib` to make sure your jars are there.
You probably did not run `gae/libs`.

== the code

See the README for https://github.com/migae/boot-gae for more info.
